import { Link, NavLink, Outlet, useParams } from 'react-router-dom';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useChain, useChains, useOverview, useStateInfo, usePublicOverview, usePublicChains, usePublicChain } from './api/hooks';
import { apiFetch, post, put, setToken } from './api/client';
import type { ChainRow, EndpointRow, Overview } from './api/types';
import { hitRate, isHttpUrl, qpsFromSnapshots, rpcUrl, statusMeta } from './utils';
import { confirmAction } from './confirm';
import { CurlExample } from './CurlExample';

const fmt = (n: number) => new Intl.NumberFormat().format(n);
const Status = ({ state }: { state: string }) => { const [color, text] = statusMeta(state); return <span className="status"><i style={{ background: color }} />{text}</span> };
function ErrorBox({ error }: { error: unknown }) { return <div className="error">{error instanceof Error ? error.message : 'Request failed'}</div> }
function showError(error: unknown) { window.alert(error instanceof Error ? error.message : 'Request failed') }

export function Layout() { const [unauthorized,setUnauthorized]=useState(false); useEffect(()=>{const handler=()=>setUnauthorized(true);window.addEventListener('rpcrouter:unauthorized',handler);return()=>window.removeEventListener('rpcrouter:unauthorized',handler)},[]); return <><header><Link to="/dashboard/" className="brand">rpcrouter</Link><nav><NavLink to="/dashboard/" end>Overview</NavLink><NavLink to="/dashboard/chains">Chains</NavLink><NavLink to="/dashboard/settings">Settings</NavLink><Link to="/">Public site</Link></nav></header><main>{unauthorized&&<div className="error">Authorization failed. Update the bearer token in <Link to="/dashboard/settings" onClick={()=>setUnauthorized(false)}>Settings</Link>.</div>}<Outlet /></main></> }
const writable = (x: ReturnType<typeof useStateInfo>['data']) => x?.writable !== false;

export function OverviewPage() {
  const interval = Number(localStorage.getItem('rpcrouter.pollMs') || 2000); const { data, isLoading, error } = useOverview(interval); const writableState = writable(useStateInfo(interval).data); const previous = useRef<{ at: number; value: Overview }>(); const [samples, setSamples] = useState<{ at:number; t: string; qps: number; hit: number }[]>([]);
  useEffect(() => { if (!data) return; const now = Date.now(); const old = previous.current; const qps = qpsFromSnapshots(old?.value, data, old ? (now - old.at) / 1000 : 0); setSamples(s => [...s, { at:now, t: new Date(now).toLocaleTimeString(), qps, hit: hitRate(data.traffic) }].filter(x=>x.at>=now-300000)); previous.current = { at: now, value: data }; }, [data]);
  if (isLoading) return <p>Loading overview…</p>; if (error) return <ErrorBox error={error} />; if (!data) return null;
  const clear = () => post('/admin/api/cache/clear').catch(showError); const refresh = () => post('/admin/api/chainlist/refresh').catch(showError); const tiles: [string, number | string][] = [['Catalog chains', data.chains.catalog], ['Active endpoints', data.endpoints.active], ['Cooling / probation', `${data.endpoints.cooling} / ${data.endpoints.probation}`], ['Ingress QPS', samples.at(-1)?.qps.toFixed(1) || '0'], ['Cache hit rate', `${hitRate(data.traffic).toFixed(1)}%`], ['User-visible errors', data.traffic.userVisibleErrorsTotal], ['In flight', data.traffic.inFlight], ['Probe queue', data.probe.queueDepth]];
  return <section>{!writableState && <div className="warning">State store is read-only. Control actions are disabled.</div>}<div className="page-title"><div><h1>Overview</h1><p className="muted">{data.chainlist.source} · last refresh {data.chainlist.lastRefreshUnix ? new Date(data.chainlist.lastRefreshUnix * 1000).toLocaleString() : 'unknown'}</p></div><div className="actions"><button disabled={!writableState} onClick={refresh}>Refresh chainlist</button><button disabled={!writableState} onClick={clear}>Clear cache</button></div></div><div className="tiles">{tiles.map(([label, value]) => <article className="tile" key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div><div className="card chart"><h2>Traffic (last 5 minutes)</h2><ResponsiveContainer width="100%" height={210}><LineChart data={samples}><XAxis dataKey="t" hide /><YAxis /><Tooltip /><Line type="monotone" dataKey="qps" stroke="#2a78d6" strokeWidth={2} dot={false} name="QPS" /><Line type="monotone" dataKey="hit" stroke="#1baf7a" strokeWidth={2} dot={false} name="Hit %" /></LineChart></ResponsiveContainer><table className="chart-table"><thead><tr><th>Time</th><th>QPS</th><th>Hit rate</th></tr></thead><tbody>{samples.slice(-5).reverse().map(x=><tr key={x.at}><td>{x.t}</td><td>{x.qps.toFixed(1)}</td><td>{x.hit.toFixed(1)}%</td></tr>)}</tbody></table></div></section>
}

export function ChainsPage() {
  const [q, setQ] = useState(''); const [state, setState] = useState('all'); const [testnet, setTestnet] = useState(''); const [sort, setSort] = useState('priority'); const [page, setPage] = useState(0); const [rates, setRates] = useState<Record<number, number>>({}); const previous = useRef<{ at: number; totals: Record<number, number> }>(); const params = useMemo(() => { const x = new URLSearchParams({ state: state === 'candidates' ? 'all' : state, sort, limit: '50', offset: String(page * 50) }); if (q) x.set('q', q); if (testnet) x.set('testnet', testnet); return x }, [q, state, testnet, sort, page]); const { data, isLoading, error, refetch } = useChains(params, state === 'dormant' ? 60000 : 5000);
  const candidateRows = state === 'candidates' ? (data?.items.filter(r => r.autoCandidate) || []) : data?.items; const writableState = writable(useStateInfo(5000).data);
  useEffect(() => { if (!data) return; const now = Date.now(); const old = previous.current; const totals = Object.fromEntries(data.items.map(row => [row.chainId, row.ingressTotal])); if (old) { const seconds = (now - old.at) / 1000; setRates(Object.fromEntries(data.items.map(row => [row.chainId, Math.max(0, row.ingressTotal - (old.totals[row.chainId] || row.ingressTotal)) / seconds]))) } previous.current = { at: now, totals } }, [data]);
  const action = (id: number, name: string) => confirmAction(`${name} chain ${id}?`, () => post(`/admin/api/chains/${id}/${name}`).then(() => refetch()).catch(showError));
  return <section>{!writableState && <div className="warning">State store is read-only. Control actions are disabled.</div>}<div className="page-title"><div><h1>Chains</h1><p className="muted">{data?.total ?? 0} matching chains</p></div></div><div className="filters"><input placeholder="Search name, short name, chain id" value={q} onChange={e => { setPage(0); setQ(e.target.value) }} /><select value={state} onChange={e => { setPage(0); setState(e.target.value) }}><option value="all">All states</option><option value="candidates">Candidates</option>{['pinned', 'hot', 'dormant', 'disabled'].map(x => <option key={x}>{x}</option>)}</select><select value={testnet} onChange={e => setTestnet(e.target.value)}><option value="">All networks</option><option value="false">Mainnet</option><option value="true">Testnet</option></select><select value={sort} onChange={e => setSort(e.target.value)}><option value="priority">Priority</option><option value="traffic">Traffic</option><option value="chainId">Chain ID</option><option value="name">Name</option></select></div>{error ? <ErrorBox error={error} /> : isLoading ? <p>Loading…</p> : <><div className="table-wrap"><table><thead><tr><th>Chain</th><th>Pin source</th><th>Status</th><th>Endpoints</th><th>Head</th><th>QPS</th><th>Hit rate</th><th>UVE</th><th>Actions</th></tr></thead><tbody>{candidateRows?.map(row => <ChainTableRow key={row.chainId} row={row} rate={rates[row.chainId] || 0} writableState={writableState} action={action} />)}</tbody></table></div><div className="pager"><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1}</span><button disabled={!data || (page + 1) * 50 >= data.total} onClick={() => setPage(page + 1)}>Next</button></div></>}</section>
}
function ChainTableRow({ row, rate, writableState, action }: { row: ChainRow; rate: number; writableState: boolean; action: (id: number, name: string) => void }) { return <tr><td><Link to={`/dashboard/chains/${row.chainId}`}><strong>{row.name}</strong></Link><small>{row.shortName || row.chainId}</small></td><td>{row.pinSource || '—'}{row.autoCandidate && <small>round {row.autoCandidate.rounds}{row.autoCandidate.lastError ? ` · ${row.autoCandidate.lastError}` : ''}</small>}</td><td><Status state={row.state} /></td><td>{row.active}/{row.endpoints}</td><td>{fmt(row.head)}</td><td>{rate.toFixed(1)}</td><td>{row.cacheLookupsTotal ? `${(row.cacheHitsTotal / row.cacheLookupsTotal * 100).toFixed(1)}%` : '—'}</td><td>{row.userVisibleErrorsTotal}</td><td className="row-actions"><button disabled={!writableState} onClick={() => action(row.chainId, 'activate')}>Activate</button><button disabled={!writableState} onClick={() => action(row.chainId, row.pinned ? 'unpin' : 'pin')}>{row.pinned ? 'Unpin' : 'Pin'}</button><button disabled={!writableState} onClick={() => action(row.chainId, row.disabled ? 'enable' : 'disable')}>{row.disabled ? 'Enable' : 'Disable'}</button></td></tr> }

export function ChainDetailPage() {
  const { id } = useParams(); const interval = Number(localStorage.getItem('rpcrouter.pollMs') || 2000); const { data, isLoading, error, refetch } = useChain(id, interval); const [settings, setSettings] = useState<Record<string, string>>({}); const writableState = writable(useStateInfo(interval).data); if (isLoading) return <p>Loading…</p>; if (error) return <ErrorBox error={error} />; if (!data) return null;
  const endpoints: EndpointRow[] = data.endpointRows || []; const endpointAction = (action: string, url: string, body: Record<string, unknown> = {}) => confirmAction(`${action} endpoint ${url}?`, () => post(`/admin/api/chains/${id}/endpoints/${action}`, { url, ...body }).then(() => refetch()).catch(showError)); const save = () => put(`/admin/api/chains/${id}/settings`, Object.fromEntries(Object.entries(settings).map(([k, v]) => [k, v === '' ? null : Number(v)]))).then(() => refetch()).catch(showError); const effective = data.settings as Record<string, number | string | undefined>;
  return <section>{!writableState && <div className="warning">State store is read-only. Control actions are disabled.</div>}<div className="page-title"><div><Link to="/dashboard/chains">← Chains</Link><h1>{data.name} <Status state={data.state} /></h1></div></div><CurlExample chainId={id || ''} /><div className="card"><h2>Chain parameters</h2><p className="muted">Source: {data.settings.source || 'default'}</p><div className="param-grid">{['blockTimeMs', 'confirmationDepth', 'tipTtlMs', 'maxBlockLag'].map(k => <label key={k}>{k}<input type="number" value={settings[k] ?? String(effective[k] ?? '')} onChange={e => setSettings({ ...settings, [k]: e.target.value })} /></label>)}</div><button disabled={!writableState} onClick={save}>Save settings</button></div><AddEndpoint id={id || ''} writableState={writableState} done={() => refetch()} /><div className="card table-wrap"><h2>Endpoints ({endpoints.length})</h2><table><thead><tr><th>URL</th><th>State</th><th>Strikes</th><th>Latency</th><th>Lag</th><th>RPS / concurrency</th><th>Stats</th><th>Actions</th></tr></thead><tbody>{endpoints.map(e => <tr key={e.url}><td><code>{e.url}</code><small>{e.source}{e.lastFault ? ` · ${e.lastFault}` : ''}</small></td><td><Status state={e.disabled ? 'disabled' : e.state} /></td><td>{e.strikes}</td><td>{e.latencyEwmaMs.toFixed(1)} ms</td><td>{e.lag}</td><td>{e.rps} / {e.concurrency}</td><td>{e.stats.outboundRequests} req · {e.stats.failures} fail · {e.stats.rateLimited} 429 · {e.stats.coolingEvents} cool</td><td className="row-actions"><button disabled={!writableState} onClick={() => endpointAction(e.disabled ? 'enable' : 'disable', e.url)}>{e.disabled ? 'Enable' : 'Disable'}</button><button disabled={!writableState} onClick={() => endpointAction('cool', e.url, { seconds: 60 })}>Cool</button><button disabled={!writableState} onClick={() => endpointAction('reset', e.url)}>Reset</button><button disabled={!writableState} onClick={() => endpointAction('probe', e.url)}>Probe</button><button disabled={!writableState} onClick={() => { const rps = window.prompt('RPS limit', String(e.rps)); const concurrency = window.prompt('Concurrency limit', String(e.concurrency)); if (rps && concurrency) endpointAction('limits', e.url, { rps: Number(rps), concurrency: Number(concurrency) }) }}>Limits</button></td></tr>)}</tbody></table></div></section>
}
function AddEndpoint({ id, writableState, done }: { id: string; writableState: boolean; done: () => void }) { const [url, setUrl] = useState(''); return <div className="card inline-form"><h2>Add endpoint</h2><input type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://rpc.example" /><button disabled={!url || !writableState} onClick={() => confirmAction(`Add endpoint ${url}?`, () => post(`/admin/api/chains/${id}/endpoints/add`, { url }).then(() => { setUrl(''); done() }).catch(showError))}>Add</button></div> }

export function SettingsPage() {
  const [token, setTokenState] = useState(localStorage.getItem('rpcrouter.adminToken') || ''); const [poll, setPoll] = useState(localStorage.getItem('rpcrouter.pollMs') || '2000'); const [theme, setTheme] = useState(localStorage.getItem('rpcrouter.theme') || 'system'); const { data, error, refetch } = useStateInfo(Number(poll)); const writableState = writable(data); useEffect(() => { document.documentElement.dataset.theme = theme }, [theme]); const save = () => { setToken(token); localStorage.setItem('rpcrouter.pollMs', poll); localStorage.setItem('rpcrouter.theme', theme); document.documentElement.dataset.theme = theme }; const download = async () => { const x = await apiFetch('/admin/api/state/export'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(x, null, 2)], { type: 'application/json' })); a.download = 'rpcrouter-state.json'; a.click() }; const reset = () => confirmAction('Reset all persisted state? This cannot be undone.', () => post('/admin/api/state/reset', { confirm: true }).then(() => refetch()).catch(showError));
  return <section><h1>Settings</h1><div className="card settings"><label>Admin token<input type="password" value={token} onChange={e => setTokenState(e.target.value)} placeholder="Bearer token" /></label><label>Polling interval (ms)<input type="number" min="500" value={poll} onChange={e => setPoll(e.target.value)} /></label><label>Theme<select value={theme} onChange={e => setTheme(e.target.value)}><option value="system">Follow system</option><option value="light">Light</option><option value="dark">Dark</option></select></label><button onClick={save}>Save settings</button></div><div className="card"><h2>State storage</h2>{!writableState && <div className="warning">State store is read-only. Import/reset controls are disabled.</div>}{error ? <ErrorBox error={error} /> : data && <dl className="state-grid"><dt>Backend</dt><dd>{data.backend}</dd><dt>Connectivity</dt><dd>{data.up ? 'Up' : 'Down'}</dd><dt>Writable</dt><dd>{data.writable ? 'Yes' : 'No'}</dd><dt>Namespace</dt><dd>{data.namespace}</dd><dt>Dirty endpoints</dt><dd>{data.dirtyEndpoints}</dd><dt>Last flush</dt><dd>{data.lastFlushUnix ? new Date(data.lastFlushUnix * 1000).toLocaleString() : '—'}</dd></dl>}<div className="actions"><button onClick={download}>Export JSON</button><label className="button">Import JSON<input disabled={!writableState} type="file" accept="application/json" hidden onChange={async e => { const file = e.target.files?.[0]; if (file) await post('/admin/api/state/import', JSON.parse(await file.text())).then(() => refetch()).catch(showError) }} /></label><button className="danger" disabled={!writableState} onClick={reset}>Reset state</button></div></div></section>
}

export function PublicLayout() {
  return <><header><Link to="/" className="brand">rpcrouter</Link><nav><Link to="/">Public site</Link><Link to="/dashboard/">Dashboard</Link></nav></header><main><Outlet /></main></>;
}

function CopyRpcUrl({ chainId }: { chainId: number }) {
  const url = rpcUrl(window.location.origin, chainId); const [copied, setCopied] = useState(false);
  return <span className="rpc-copy"><code>{url}</code><button onClick={() => navigator.clipboard?.writeText(url).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1500) }).catch(() => undefined)}>{copied ? 'Copied' : 'Copy'}</button></span>;
}

export function PublicHomePage() {
  const { data: overview, isLoading: loadingOverview, error: overviewError } = usePublicOverview();
  const [q, setQ] = useState(''); const [testnet, setTestnet] = useState(''); const [page, setPage] = useState(0);
  const [debouncedQ, setDebouncedQ] = useState(q); useEffect(() => { const timer = setTimeout(() => setDebouncedQ(q), 300); return () => clearTimeout(timer) }, [q]);
  const params = useMemo(() => { const p = new URLSearchParams({ sort: 'priority', limit: '50', offset: String(page * 50) }); if (debouncedQ) { p.set('q', debouncedQ); p.set('scope', 'all'); } if (testnet) p.set('testnet', testnet); return p }, [debouncedQ, testnet, page]);
  const { data, isLoading, error } = usePublicChains(params);
  if (loadingOverview) return <p>Loading…</p>; if (overviewError || !overview) return <ErrorBox error={overviewError || new Error('Request failed')} />; if (!data && isLoading) return <p>Loading chains…</p>;
  const origin = window.location.origin; const hit = overview.traffic.cacheLookupsTotal ? overview.traffic.cacheHitsTotal / overview.traffic.cacheLookupsTotal * 100 : 0;
  return <section><div className="page-title"><div><h1>Public RPC access</h1><p className="muted">Fast, read-only access to public blockchain RPC endpoints.</p></div></div><div className="card"><h2>Connect to any chain</h2><p>Use the chain-specific endpoint template <code>{origin}/rpc/{'{chainId}'}</code>. Replace <code>{'{chainId}'}</code> with the chain id from the table.</p><CurlExample chainId="{chainId}" title="Quick start" /></div><div className="tiles"><article className="tile"><span>Chains serving</span><strong>{overview.chains.serving}</strong></article><article className="tile"><span>Active endpoints</span><strong>{overview.endpoints.active}</strong></article><article className="tile"><span>Requests served</span><strong>{fmt(overview.traffic.ingressTotal)}</strong></article><article className="tile"><span>Cache hit rate</span><strong>{hit.toFixed(1)}%</strong></article></div><div className="filters"><input aria-label="Search chains" maxLength={64} placeholder="Search all chains by name, short name, chain id" value={q} onChange={e => { setPage(0); setQ(e.target.value) }} /><select aria-label="Network" value={testnet} onChange={e => { setPage(0); setTestnet(e.target.value) }}><option value="">All networks</option><option value="false">Mainnet</option><option value="true">Testnet</option></select><span /><span /></div>{error && <ErrorBox error={error} />}<div className="card table-wrap"><table><thead><tr><th>Chain</th><th>Chain ID</th><th>Status</th><th>Endpoints</th><th>Head</th><th>RPC URL</th></tr></thead><tbody>{data?.items.map(row => <tr key={row.chainId}><td><Link to={`/chain/${row.chainId}`}><strong>{row.name}</strong></Link><small>{row.shortName || '—'}</small></td><td>{row.chainId}</td><td><Status state={row.state} />{row.state === 'dormant' && <small>Available (on demand)</small>}{row.status && !['active', row.state].includes(row.status) && <small>{row.status}</small>}</td><td>{row.active}/{row.endpoints}</td><td>{fmt(row.head)}</td><td><CopyRpcUrl chainId={row.chainId} /></td></tr>)}</tbody></table></div><div className="pager"><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1}</span><button disabled={!data || (page + 1) * 50 >= data.total} onClick={() => setPage(page + 1)}>Next</button></div></section>;
}

export function PublicChainPage() {
  const { id } = useParams(); const { data, isLoading, error } = usePublicChain(id); if (isLoading) return <p>Loading…</p>; if (error) return <ErrorBox error={error} />; if (!data) return null;
  return <section><p><Link to="/">← All chains</Link></p><div className="page-title"><div><h1>{data.name}</h1><p className="muted">Chain ID {data.chainId} · <Status state={data.state} /></p></div></div><div className="tiles"><article className="tile"><span>Native token</span><strong>{data.nativeSymbol || '—'}</strong></article><article className="tile"><span>Endpoints</span><strong>{data.active}/{data.endpoints}</strong></article><article className="tile"><span>Head</span><strong>{fmt(data.head)}</strong></article></div><div className="card"><h2>RPC endpoint</h2><p><code>{rpcUrl(window.location.origin, data.chainId)}</code></p>{isHttpUrl(data.explorerUrl) && <p><a href={data.explorerUrl} target="_blank" rel="noreferrer">Block explorer</a></p>}</div><CurlExample chainId={data.chainId} method="eth_blockNumber" /><CurlExample chainId={data.chainId} method="eth_chainId" /></section>;
}
