export type ChainState = 'active' | 'probation' | 'cooling' | 'error' | 'dormant' | 'disabled' | string;
export interface Settings { blockTimeMs?: number; confirmationDepth?: number; tipTtlMs?: number; maxBlockLag?: number; source?: string }
export interface EndpointStats { outboundRequests: number; failures: number; rateLimited: number; coolingEvents: number; probeSuccesses: number }
export interface EndpointRow { url: string; tracking?: string; state: ChainState; strikes: number; coolingUntilUnix?: number; latencyEwmaMs: number; lag: number; rps: number; concurrency: number; disabled: boolean; source: string; lastFault?: string; stats: EndpointStats }
export interface AutoCandidate { rounds: number; lastQualified?: boolean; lastError?: string }
export interface ChainRow { chainId: number; name: string; shortName?: string; isTestnet: boolean; status?: string; state: ChainState; pinned: boolean; disabled: boolean; catalogEndpoints: number; endpoints: number; active: number; cooling: number; probation: number; head: number; lastIngressUnix: number; ingressTotal: number; cacheHitsTotal: number; cacheLookupsTotal: number; upstreamTotal: number; userVisibleErrorsTotal: number; settings: Settings; pinSource?: 'config' | 'manual' | 'auto' | null; autoCandidate?: AutoCandidate; endpointRows?: EndpointRow[] }
export interface Overview { process: { version: string; uptimeSeconds: number }; chainlist: { source: string; lastRefreshUnix: number; etag?: string; catalogChains: number; catalogEndpoints: number; refreshSeconds: number; lastError?: string; refreshing: boolean }; chains: { catalog: number; pinned: number; hot: number; dormant: number; disabled: number }; autoEnable?: { enabled: boolean; chains: number; candidates: number; pending: number; capped: boolean; lastScanAt?: number; promotionsTotal: number }; endpoints: { materialized: number; active: number; cooling: number; probation: number }; traffic: { ingressTotal: number; cacheHitsTotal: number; cacheLookupsTotal: number; coalescedTotal: number; upstreamTotal: number; userVisibleErrorsTotal: number; ingressRejectedTotal: number; hedgesTotal: number; inFlight: number }; state?: { backend: string; overrides: number }; probe: { queueDepth: number; inFlight: number; maxConcurrency: number }; cache: { entries: number; weightedBytes: number; maxBytes: number } }
export interface ChainList { total: number; items: ChainRow[] }
export interface PublicChainRow { chainId: number; name: string; shortName?: string; isTestnet: boolean; nativeSymbol?: string; explorerUrl?: string; status?: string; state: string; catalogEndpoints: number; endpoints: number; active: number; head: number; ingressTotal: number; cacheHitsTotal: number; cacheLookupsTotal: number }
export interface PublicChainList { total: number; items: PublicChainRow[] }
export interface PublicOverview { process: { version: string; uptimeSeconds: number }; chains: { catalog: number; pinned: number; hot: number; dormant: number; disabled: number; serving: number; available?: number }; endpoints: { materialized: number; active: number }; traffic: { ingressTotal: number; cacheHitsTotal: number; cacheLookupsTotal: number; upstreamTotal: number }; rpc: { pathTemplate: string } }
export interface StateInfo { backend: string; namespace: string; instanceId: string; up: boolean; writable: boolean; schemaVersion: number; dirtyEndpoints: number; lastFlushUnix: number; lastFlushResult?: string; lastFlushDurationMs: number; lastPingUnix: number }
export interface StateExport { schema_version?: number; catalog?: unknown; overrides: { chains: Record<string, unknown>; endpoints: Record<string, unknown> }; health?: unknown[]; hot_chains?: unknown[] }
